Add error messages, listing recordings & start of ghosts
oberien/refunct-tas pull request #85
Opened 2022-04-14 19:52 UTC by LukeSaward1

2022-04-17 23:59 UTC, LukeSaward1 commented
DON'T REVIEW UNTIL I'VE MERGED LATEST [WILL EDIT ONCE I'VE MERGED]

2022-04-18 10:15 UTC, oberien requested changes
#### Recording Name
My suggestion for the recording name was to reuse the multiplayer name for the recording name and make it configurable at three locations (settings, multiplayer, save recording). That way we only have a single name stored and not individual names for every single functionality.

#### Recording Menu

For the save recording menu, I imagine an input field for a file name at the top and one button per existing recording below. If the input field is submitted, then the recording of the input field name is taken. If a button of an existing recording is pressed, then that recording is overwritten.

Similarly for load recording and delete recording I'd only show one button per recording without an input field (or with an input field for olivia as the list of existing recordings may get too long? ;) ).

What do you think about that?

2022-04-18 14:08 UTC, LukeSaward1 commented
> Thanks for the PR, good changes. The code also starts to look cleaner and more idiomatic!
> 
> #### Recording Name
> My suggestion for the recording name was to reuse the multiplayer name for the recording name and make it configurable at three locations (settings, multiplayer, save recording). That way we only have a single name stored and not individual names for every single functionality.
> 
> #### Recording Menu
> For the save recording menu, I imagine an input field for a file name at the top and one button per existing recording below. If the input field is submitted, then the recording of the input field name is taken. If a button of an existing recording is pressed, then that recording is overwritten.
> 
> Similarly for load recording and delete recording I'd only show one button per recording without an input field (or with an input field for olivia as the list of existing recordings may get too long? ;) ).
> 
> What do you think about that?
> 
> #### Git
> Instead of merging oberien/master into your branch, then merging oberien/master into your branch, then doing a commit, then merging oberien/master into your branch, then doing a commit, you should use rebase as it keeps the history cleaner. I can explain this more to you in discord if you want (or you can try reading into it, though I don't know how good the resources are surrounding that).

Will do.

2022-04-20 10:51 UTC, oberien requested changes

2022-04-20 10:51 UTC, oberien commented on tool/main.re
> +}
This function isn't used.

2022-04-20 10:51 UTC, oberien commented on tool/main.re
> +static mut SAVE_RECORDING_LABEL = Text { text: "Save Recording" };
This static isn't used.

2022-04-20 10:51 UTC, oberien commented on tool/main.re
> +            }));
This is the one time I'd put the "Back" button at the beginning. Otherwise it may not be visible on lower resolution screens.

2022-04-20 10:51 UTC, oberien commented on tool/main.re
> +                        tas_save_recording(label.text);
You probably want to `leave_ui()`.

2022-04-20 10:51 UTC, oberien commented on tool/main.re
> +            enter_ui(recording_options_menu);
No need for the additional variable.

2022-04-20 12:25 UTC, oberien requested changes

2022-04-20 12:25 UTC, oberien commented on tool/main.re
> +            }));
Can be combined into `List::of(UiElement::Button...`.

2022-04-20 12:25 UTC, oberien commented on tool/main.re
>  }
This is not what I meant with https://github.com/oberien/refunct-tas/pull/85#discussion_r853996914. As you can see, you needed to call this function from three different places. In all of those three places you needed to change the code to have the `Back` button as first element of the list. Try refactoring all of the triplicated code into one function, such that a change like moving the `Back` button will only need to be changed in a single place.

2022-04-20 12:26 UTC, oberien commented on tool/main.re
> +                        leave_ui();
superseded by https://github.com/oberien/refunct-tas/pull/85#discussion_r854072592

2022-04-20 18:08 UTC, oberien commented
superseded by #102

2022-04-20 18:08 UTC, closed without merging